display:
  cycle: true
  inverted: false
  orientation: 270
mining:
  display: unpaid,wallet
  walletcurrency: cad
  enabled: true
  key: 
  organisation: 
  secret: 
ticker:
  coinname: true
  currency: ravencoin,bitcoin,ethereum,stellar,bitcoin-cash,monero,mithril,litecoin
  exchange: default
  fiatcurrency: cad
  sparklinedays: 7
  updatefrequency: 30

